### ISSUE TITLE
[bug - menuDirectory] Failure to properly read multi-level nav that are not collections 

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-backend#30]
If the `navigation.yml` file contains a multi-level nav that isn't a collection, it would just treat the first link as a simple page, as the way we detect for simple pages is to check if it has an attribute `url` (refer to example below).

```
links:
  - title: Digital Gov Transformation
    url: /digital-government-transformation/
    sublinks:
    - title: Overview
      url: /digital-government-transformation/
    - title: Digital Government Blueprint
      url: /digital-government-blueprint/
    - title: Products and Services
      url: /products-and-services/
    - title: Digital Standards and Guides
      url: /digital-standards-and-guides/
    - title: Get Involved
      url: /get-involved/
```

We can deal with this by testing for the `sublinks` attribute and introducing new object types in the drag and drop menu to account for this new type of nav item.
